version: "3"
services:
  nginx:
    build:
      context: ./service/nginx
      args:
        TZ: "${TZ}"
        VERSION: ${NGINX_VERSION}
    ports: # 宿主机:容器
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${DIR_WWW}:/www
      - ${DIR_CONFIG}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DIR_CONFIG}/nginx/conf.d:/etc/nginx/conf.d
      - ${DIR_LOG}/nginx/log:/var/log/nginx
    restart: always
    container_name: nginx

  mysql:
    build:
      context: ./service/mysql
      args:
        TZ: "${TZ}"
        VERSION: ${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DIR_DATA}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    container_name: mysql

  redis:
    build:
      context: ./service/redis
      args:
        TZ: "${TZ}"
        VERSION: ${REDIS_VERSION}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DIR_CONFIG}/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${DIR_DATA}/redis:/data
    restart: always
    container_name: redis

  php72:
    build:
      context: ./service/php/php72
      args:
        TZ: "${TZ}"
        VERSION: ${PHP72_VERSION}
    ports:
      - "${PHP72_FPM_PORT}:9000"
    volumes:
      - ${DIR_WWW}:/www
      - ${DIR_CONFIG}/php/php.ini:/usr/local/etc/php/php.ini
      - ${DIR_CONFIG}/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${DIR_LOG}/php:/var/log/php
    restart: always
    container_name: php72

  #  php56:
  #    build:
  #      context: ./service/php/php56
  #      args:
  #        TZ: "${TZ}"
  #        VERSION: ${PHP56_VERSION}
  #    ports:
  #      - "${PHP56_FPM_PORT}:9000"
  #    volumes:
  #      - ${DIR_WWW}:/www
  #      - ${DIR_CONFIG}/php/php.ini:/usr/local/etc/php/php.ini
  #      - ${DIR_CONFIG}/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
  #      - ${DIR_LOG}/php:/var/log/php
  #    restart: always
  #    container_name: php56

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    container_name: phpmyadmin