version: "3"
services:
  nginx:
    build: ./service/nginx
    depends_on:
      - "php"
    ports: # 宿主机:容器
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ${DIR_WWW}:/www
      - ${DIR_CONFIG}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${DIR_CONFIG}/nginx/conf.d:/etc/nginx/conf.d
      - ${DIR_LOG}/nginx/log:/var/log/nginx
    restart: always
    container_name: nginx

  php:
    build: ./service/php
    ports:
      - "${PHP_FPM_PORT}:9000"
    volumes:
      - ${DIR_WWW}:/www
      - ${DIR_CONFIG}/php/php.ini:/usr/local/etc/php/php.ini
      - ${DIR_CONFIG}/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    restart: always
    container_name: php

  mysql:
    build: ./service/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DIR_DATA}/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    container_name: mysql
